/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContribuaRouteImport } from './routes/contribua'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as InstitutoRouteImport } from './routes/instituto'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LojaIndexRouteImport } from './routes/loja.index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as MensagensIndexRouteImport } from './routes/mensagens.index'
import { Route as MensagensSlugRouteImport } from './routes/mensagens.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuaRoute = ContribuaRouteImport.update({
  id: '/contribua',
  path: '/contribua',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutoRoute = InstitutoRouteImport.update({
  id: '/instituto',
  path: '/instituto',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensIndexRoute = MensagensIndexRouteImport.update({
  id: '/mensagens/',
  path: '/mensagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensSlugRoute = MensagensSlugRouteImport.update({
  id: '/mensagens/$slug',
  path: '/mensagens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/contribua': typeof ContribuaRoute
  '/entrar': typeof EntrarRoute
  '/instituto': typeof InstitutoRoute
  '/play': typeof PlayRoute
  '/sobre': typeof SobreRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/loja/': typeof LojaIndexRoute
  '/mensagens/': typeof MensagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/contribua': typeof ContribuaRoute
  '/entrar': typeof EntrarRoute
  '/instituto': typeof InstitutoRoute
  '/play': typeof PlayRoute
  '/sobre': typeof SobreRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/loja': typeof LojaIndexRoute
  '/mensagens': typeof MensagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contato': typeof ContatoRoute
  '/contribua': typeof ContribuaRoute
  '/entrar': typeof EntrarRoute
  '/instituto': typeof InstitutoRoute
  '/play': typeof PlayRoute
  '/sobre': typeof SobreRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/loja/': typeof LojaIndexRoute
  '/mensagens/': typeof MensagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/contato'
    | '/contribua'
    | '/entrar'
    | '/instituto'
    | '/play'
    | '/sobre'
    | '/loja/$slug'
    | '/mensagens/$slug'
    | '/loja/'
    | '/mensagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/contato'
    | '/contribua'
    | '/entrar'
    | '/instituto'
    | '/play'
    | '/sobre'
    | '/loja/$slug'
    | '/mensagens/$slug'
    | '/loja'
    | '/mensagens'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/contato'
    | '/contribua'
    | '/entrar'
    | '/instituto'
    | '/play'
    | '/sobre'
    | '/loja/$slug'
    | '/mensagens/$slug'
    | '/loja/'
    | '/mensagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ContatoRoute: typeof ContatoRoute
  ContribuaRoute: typeof ContribuaRoute
  EntrarRoute: typeof EntrarRoute
  InstitutoRoute: typeof InstitutoRoute
  PlayRoute: typeof PlayRoute
  SobreRoute: typeof SobreRoute
  LojaSlugRoute: typeof LojaSlugRoute
  MensagensSlugRoute: typeof MensagensSlugRoute
  LojaIndexRoute: typeof LojaIndexRoute
  MensagensIndexRoute: typeof MensagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribua': {
      id: '/contribua'
      path: '/contribua'
      fullPath: '/contribua'
      preLoaderRoute: typeof ContribuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituto': {
      id: '/instituto'
      path: '/instituto'
      fullPath: '/instituto'
      preLoaderRoute: typeof InstitutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/': {
      id: '/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof MensagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/$slug': {
      id: '/mensagens/$slug'
      path: '/mensagens/$slug'
      fullPath: '/mensagens/$slug'
      preLoaderRoute: typeof MensagensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ContatoRoute: ContatoRoute,
  ContribuaRoute: ContribuaRoute,
  EntrarRoute: EntrarRoute,
  InstitutoRoute: InstitutoRoute,
  PlayRoute: PlayRoute,
  SobreRoute: SobreRoute,
  LojaSlugRoute: LojaSlugRoute,
  MensagensSlugRoute: MensagensSlugRoute,
  LojaIndexRoute: LojaIndexRoute,
  MensagensIndexRoute: MensagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
